export const TYPES = {
  SET_BLOGS: 'SET_BLOGS',
  SET_BLOG: 'SET_BLOG',
  TOGGLE_MODE: 'TOGGLE_MODE',
  SET_LOADING: 'SET_LOADING',
  SET_EXAMPLE_TITLE: 'SET_EXAMPLE_TITLE',
  SET_PROFILE: 'SET_PROFILE',
};
